spring:
  application:
    name: langchain4j-study

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ${DASHSCOPE_API_KEY}
  memory:
    message:
      maxCount: 50